//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Diagnostics;

    public partial class dbProdavnicaNamestajaEntities : DbContext
    {
        public dbProdavnicaNamestajaEntities()
            : base("name=dbProdavnicaNamestajaEntities")
        {
            Database.Log = sql => Debug.Write(sql);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdrese> tblAdrese { get; set; }
        public virtual DbSet<tblKategorijeNamestaja> tblKategorijeNamestaja { get; set; }
        public virtual DbSet<tblKomadiNamestaja> tblKomadiNamestaja { get; set; }
        public virtual DbSet<tblKorisnici> tblKorisnici { get; set; }
        public virtual DbSet<tblRacuni> tblRacuni { get; set; }
        public virtual DbSet<tblSaloni> tblSaloni { get; set; }
        public virtual DbSet<tblUloge> tblUloge { get; set; }
    }
}
