//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdrese
    {
        public int IdAdrese { get; set; }
        public string Ulica { get; set; }
        public string Broj { get; set; }
        public string Mesto { get; set; }
        public Nullable<int> IdKorisnika { get; set; }
        public Nullable<int> IdSalona { get; set; }
    
        public virtual tblKorisnici tblKorisnici { get; set; }
        public virtual tblSaloni tblSaloni { get; set; }
    }
}
