//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKomadiNamestaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKomadiNamestaja()
        {
            this.tblRacuni = new HashSet<tblRacuni>();
        }
    
        public int IdNamestaja { get; set; }
        public string Sifra { get; set; }
        public string Naziv { get; set; }
        public string ZemljaProizvodnje { get; set; }
        public System.DateTime GodinaProizvodnje { get; set; }
        public decimal Cena { get; set; }
        public int Kolicina { get; set; }
        public byte[] Slika { get; set; }
        public Nullable<int> IdSalona { get; set; }
        public Nullable<int> IdKategorije { get; set; }
    
        public virtual tblKategorijeNamestaja tblKategorijeNamestaja { get; set; }
        public virtual tblSaloni tblSaloni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRacuni> tblRacuni { get; set; }
    }
}
