//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRacuni
    {
        public int IdRacuna { get; set; }
        public int Kolicina { get; set; }
        public decimal Cena { get; set; }
        public int Porez { get; set; }
        public decimal UkupnaCena { get; set; }
        public System.DateTime DatumKupovine { get; set; }
        public string NazivSalona { get; set; }
        public int IdKorisnika { get; set; }
        public int IdNamestaja { get; set; }
    
        public virtual tblKomadiNamestaja tblKomadiNamestaja { get; set; }
        public virtual tblKorisnici tblKorisnici { get; set; }
    }
}
