//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaloni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSaloni()
        {
            this.tblAdrese = new HashSet<tblAdrese>();
            this.tblKomadiNamestaja = new HashSet<tblKomadiNamestaja>();
        }
    
        public int IdSalona { get; set; }
        public string Naziv { get; set; }
        public string Vlasnik { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public byte[] WebStranica { get; set; }
        public int PIB { get; set; }
        public string BZR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdrese> tblAdrese { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKomadiNamestaja> tblKomadiNamestaja { get; set; }
    }
}
